import Header from '@/components/Header';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Next Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Toaster />
        <Header />
        <main className='flex-1 mx-auto me-auto max-w-2xl w-full flex justify-center mt-10  px-4 md:px-2'>
          {children}
        </main>
      </body>
    </html>
  );
}
